/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.java.example;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anibal
 */
public class frmJuegoDeMesa extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;
    private DefaultTableModel modeloTablaJuegos;

    /**
     * Creates new form frmJuegoDeMesa
     */
    public frmJuegoDeMesa() {
        initComponents();
        inicializarTabla();

        cargarComboCategoriaInteraccion();
        cargarComboCategoriaAccesorios();
        cargarComboMecanica();
        cargarComboProveedores();

    }

    private void cargarComboCategoriaInteraccion() {
        drpCategoriaInteraccion.addItem("Solitario");
        drpCategoriaInteraccion.addItem("1 vs 1");
        drpCategoriaInteraccion.addItem("Cooperativo");
        drpCategoriaInteraccion.addItem("Por equipos");
        drpCategoriaInteraccion.addItem("Todos contra todos");
    }

    private void cargarComboCategoriaAccesorios() {
        drpCategoriaAccesorios.addItem("De cartas");
        drpCategoriaAccesorios.addItem("De rol");
        drpCategoriaAccesorios.addItem("De fichas");
        drpCategoriaAccesorios.addItem("De miniaturas");
    }

    private void cargarComboMecanica() {
        drpMecanica.addItem("Abstracto");
        drpMecanica.addItem("Roles ocultos");
        drpMecanica.addItem("Estrategia");
        drpMecanica.addItem("Aventura");
        drpMecanica.addItem("Dungeon crawler");
    }

    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Descripción");
        tblProveedores.setModel(modeloTabla);
    }

    private void cargarComboProveedores() {
        List<Proveedor> proveedores = BLLProveedor.obtenerTodosLosProveedores();

        drpProveedor.removeAllItems();

        for (Proveedor proveedor : proveedores) {
            drpProveedor.addItem(proveedor.getDescripcion());
        }
    }

    private void actualizarTabla() {
        modeloTabla.setRowCount(0);

        for (Proveedor proveedor : BLLProveedor.obtenerTodosLosProveedores()) {
            Object[] fila = {proveedor.getIdProveedor(), proveedor.getDescripcion()};
            modeloTabla.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        drpCategoriaInteraccion = new javax.swing.JComboBox<>();
        drpCategoriaAccesorios = new javax.swing.JComboBox<>();
        drpMecanica = new javax.swing.JComboBox<>();
        txtNumeroParticipantes = new javax.swing.JTextField();
        txtEdadMinima = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        drpProveedor = new javax.swing.JComboBox<>();
        btnOpciones6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProveedores);

        jLabel1.setText("Nombre");

        jLabel2.setText("Categoria por interaccion");

        jLabel3.setText("Categoria por accesorios");

        jLabel4.setText("Mecanica");

        jLabel5.setText("Numero de Participantes");

        jLabel6.setText("Edad Minima");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel7.setText("Proveedor");

        btnOpciones6.setText("Opciones");
        btnOpciones6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpciones6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOpciones6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(drpCategoriaInteraccion, 0, 200, Short.MAX_VALUE)
                                    .addComponent(drpCategoriaAccesorios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(drpMecanica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumeroParticipantes)
                                    .addComponent(txtEdadMinima)
                                    .addComponent(drpProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(drpCategoriaInteraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(drpCategoriaAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(drpMecanica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumeroParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEdadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(drpProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnOpciones6))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        actualizarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String nombre = txtNombre.getText();
        String categoriaInteraccion = (String) drpCategoriaInteraccion.getSelectedItem();
        String categoriaAccesorios = (String) drpCategoriaAccesorios.getSelectedItem();
        String mecanica = (String) drpMecanica.getSelectedItem();
        String numeroParticipantes = txtNumeroParticipantes.getText();
        int edadMinima = Integer.parseInt(txtEdadMinima.getText());

        String proveedor = drpProveedor.getSelectedItem().toString();

        System.out.println(proveedor);

        JuegoDeMesa juegoDeMesa = new JuegoDeMesa(nombre, categoriaInteraccion, categoriaAccesorios,
                mecanica, numeroParticipantes, edadMinima, proveedor);

        BLLJuegoDeMesa.agregarJuegoDeMesa(juegoDeMesa);

        JOptionPane.showMessageDialog(this, "El juego se ha agregado correctamente.", "Juego Agregado", JOptionPane.INFORMATION_MESSAGE);

        limpiarCampos();


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnOpciones6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpciones6ActionPerformed
        frmOpciones frmOpciones = new frmOpciones();
        frmOpciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOpciones6ActionPerformed

    private void limpiarCampos() {
        txtNombre.setText("");
        drpCategoriaInteraccion.setSelectedIndex(0);
        drpCategoriaAccesorios.setSelectedIndex(0);
        drpMecanica.setSelectedIndex(0);
        txtNumeroParticipantes.setText("");
        txtEdadMinima.setText("");
        drpProveedor.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJuegoDeMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJuegoDeMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJuegoDeMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJuegoDeMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJuegoDeMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnOpciones1;
    private javax.swing.JButton btnOpciones2;
    private javax.swing.JButton btnOpciones3;
    private javax.swing.JButton btnOpciones4;
    private javax.swing.JButton btnOpciones5;
    private javax.swing.JButton btnOpciones6;
    private javax.swing.JComboBox<String> drpCategoriaAccesorios;
    private javax.swing.JComboBox<String> drpCategoriaInteraccion;
    private javax.swing.JComboBox<String> drpMecanica;
    private javax.swing.JComboBox<String> drpProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTextField txtEdadMinima;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroParticipantes;
    // End of variables declaration//GEN-END:variables
}
